service: serverless-dir
frameworkVersion: '3'

plugins:
  - serverless-offline

provider:
  name: aws
  runtime: python3.9

functions:
  function_1:
    handler: handler.function_1
    events:
      - http:
          path: /function_1
          method: get
  function_2:
    handler: handler.function_2
    events:
      - http:
          path: /function_2
          method: get
