services:
  database_1:
    build:
      context: ./database-1
      dockerfile: Dockerfile
    container_name: database_1
    restart: always
    ports:
      - 4600:3306
    volumes:
      - ./database-1/data:/var/lib/mysql
    networks:
      - final_net_1
    healthcheck:
      test: ["CMD", "mysql", "-u", "root", "-pV8e8?7?5W14R"]
      interval: 30s
      timeout: 10s
      retries: 5

  database_2:

  adminer1:
    image: adminer
    container_name: adminer_database_1
    restart: always
    ports:
      - 8001:8080
    networks:
      - final_net_1
    depends_on:
      database:
        condition: service_healthy

  adminer2:

networks:
  final_net_1:
    driver: bridge
  final_net_2:
    driver: bridge