services:
  database_1:
    build:
      context: ./database-1
      dockerfile: Dockerfile
    container_name: database_1
    restart: always
    ports:
      - 4600:3306
    volumes:
      - ./database-1/data:/var/lib/mysql
    networks:
      - final_net_1
    healthcheck:
      test: ["CMD", "mysql", "-u", "root", "-pV8e8?7?5W14R"]
      interval: 30s
      timeout: 10s
      retries: 5
  database_2:
    build:
      context: ./database-2
      dockerfile: Dockerfile
    container_name: database_2
    restart: always
    ports:
      - 4800:3306
    volumes:
      - ./database-2/data:/var/lib/mysql
    networks:
      - final_net_2
    healthcheck:
      test: ["CMD", "mysql", "-u", "root", "-pqP4!gh12t%g%12Q"]
      interval: 30s
      timeout: 10s
      retries: 5
  adminer1:
    image: adminer
    container_name: adminer_database_1
    restart: always
    ports:
      - 8001:8080
    networks:
      - final_net_1
    depends_on:
      database_1:
        condition: service_healthy
  adminer2:
    image: adminer
    container_name: adminer_database_2
    restart: always
    ports:
      - 9001:8080
    networks:
      - final_net_2
    depends_on:
      database_2:
        condition: service_healthy

networks:
  final_net_1:
    driver: bridge
  final_net_2:
    driver: bridge